[package]
name = "abra-super-resolution"
version = "1.0.0"
edition = "2024"
description = "Pre-trained models for image enhancement and restoration"

[dependencies]
abra-ai-core = { workspace = true, features = ["onnx"] }
abra-core = { workspace = true }

[lib]
crate-type = ["rlib"]
