tab_spaces = 2
max_width = 120
fn_params_layout = "Compressed"
fn_args_layout = "Compressed"
fn_call_width = 115
empty_item_single_line = false
fn_single_line = true
# array_width = 100
# single_line_if_else_max_width = 100
# single_line_let_else_max_width = 100
# format_code_in_doc_comments = true
# fn_single_line = true
