[package]
name = "image"
version = "1.0.0"
edition = "2024"

[dependencies]
core = { workspace = true }
filters = { workspace = true }
drawing = { workspace = true }

rayon = { workspace = true }
uuid = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
