[package]
name = "abra"
version = "1.0.0"
edition = "2024"

[dependencies]
core = { workspace = true }
image = { workspace = true }
drawing = { workspace = true }
adjustments = { workspace = true }
filters = { workspace = true }

rayon = { workspace = true }
