[package]
name = "abra"
version = "1.0.0"
edition = "2024"

[dependencies]
rayon = "1.10"
ndarray = { version = "0.17.1", features = ["rayon"] }
image-webp = { version = "0.2.0", optional = true }
jpeg-decoder = { version = "0.3", optional = true }
jpeg-encoder = { version = "0.6", optional = true }
png = { version = "0.18.0", optional = true }
resvg = { version = "0.45.1", optional = true }
gif = { version = "0.13.3", optional = true }

[dependencies.uuid]
version = "1.18.1"
features = ["v4"]

[features]
default = ["webp", "jpg", "png", "svg", "gif"]
webp = ["image-webp"]
jpg = ["jpeg-decoder", "jpeg-encoder"]
png = ["dep:png"]
svg = ["dep:resvg"]
gif = ["dep:gif"]
