[package]
name = "filters"
version = "1.0.0"
edition = "2024"

[dependencies]
rayon = { workspace = true }
abra-core = { workspace = true }
mask = { workspace = true }
options = { workspace = true }
adjustments = { workspace = true }

[lib]
crate-type = ["dylib", "rlib"]
