[package]
name = "core"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
rayon = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true, features = ["rayon"] }
image-webp = { version = "0.2.4", optional = true }
# jpeg-decoder = { version = "0.3.2", optional = true }
# jpeg-encoder = { version = "0.6.1", optional = true }
globwalk = { version = "0.9.1" }
# glob-match = { version = "0.2.1" }
turbojpeg = { version = "1.3.3", optional = true }
png = { version = "0.18.0", optional = true }
resvg = { version = "0.45.1", optional = true }
gif = { version = "0.14.0", optional = true }

[features]
default = ["webp", "jpg", "png", "svg", "gif"]
webp = ["image-webp"]
jpg = ["turbojpeg"]
png = ["dep:png"]
svg = ["dep:resvg"]
gif = ["dep:gif"]
