[package]
name = "core"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rayon = { workspace = true }
ndarray = { workspace = true, features = ["rayon"] }
image-webp = { version = "0.2.4", optional = true }
jpeg-decoder = { version = "0.3.2", optional = true }
jpeg-encoder = { version = "0.6.1", optional = true }
png = { version = "0.18.0", optional = true }
resvg = { version = "0.45.1", optional = true }
gif = { version = "0.14.0", optional = true }


[features]
default = ["webp", "jpg", "png", "svg", "gif"]
webp = ["image-webp"]
jpg = ["jpeg-decoder", "jpeg-encoder"]
png = ["dep:png"]
svg = ["dep:resvg"]
gif = ["dep:gif"]
