[package]
name = "super-resolution"
version = "1.0.0"
edition = "2024"

[dependencies]
abra = { workspace = true }
abra-super-resolution = { workspace = true }

[[bin]]
name = "super-resolution"
path = "main.rs"
