[package]
name = "gpu_integration"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
abra_core = { workspace = true }
gpu = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
