[package]
name = "debug"
version = "1.0.0"
edition = "2024"

[dependencies]
abra-core = { workspace = true }
canvas = { workspace = true }
rayon = { workspace = true }

[lib]
crate-type = ["dylib", "rlib"]
